[theme]
theme = "slick"
#theme = "solarized-dark"

[icons]
icons = "awesome"

[[block]]
block    = "nvidia_gpu"
gpu_id   = 1
interval = 2
format   = "$icon RTX2060 $utilization $temperature $clocks"

[[block]]
block     = "temperature"
interval  = 1

[[block]]
block    = "load"
interval = 2
format   = "$icon $1m $5m $15m"

[[block]]
block    = "cpu"
interval = 2

[[block]]
block    = "memory"
format   = "$icon $mem_used $mem_used_percents"
interval = 2

[[block]]
block = "sound"

[[block]]
#block     = "nvidia_gpu"
#gpu_id    = 0
#interval  = 2
#format    = "$icon GT710"

[[block]]
block = "uptime"

[[block]]
block    = "time"
interval = 15
format   = "$icon %a %Y/%m/%d %R"
