-- vim.api.nvim_create_autocmd("CursorHold", { pattern = { "*" }, CocActionAsync('highlight') })
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "markdown",
--   callback = function()
--     vim.treesitter.stop()
--   end,
-- })
