# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
################################################################################
#################################  Better alias  ###############################
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias df='df -h'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias ln='ln -i'
alias ports='netstat -tulanp'
alias mkdir='mkdir -pv'
alias fsize='du -h -d 1'
################################################################################
###################################  Pacman  ###################################
alias pacnor='pacman -Qt'
alias upaur='yay -Sau'
alias aurpackages='pacman -Qm'
alias orppac='pacman -Qdtq'
################################################################################
##################################  Terminal  ##################################
alias unhide='echo -en "\e[?25h"'
alias clrcnsl='printf "\033c"'
################################################################################
#################################  reboot etc ##################################
alias reboot="sudo systemctl reboot"
alias poweroff="sudo systemctl poweroff"
################################################################################
#################################  i3 save  ####################################
alias i3-resurrect-save="i3-resurrect save -d ~/.i3/i3-resurrect/"
alias i3-resurrect-restore="i3-resurrect restore -d ~/.i3/i3-resurrect/"
################################################################################
##################################  TaskWarr  ##################################
alias tprd="${MY_SHELL_UTILS}/task_populate_recurrance_dependency.sh"
################################################################################
################################  Use slert  ###################################
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
################################################################################
###########################  Use vim server ####################################
alias vimservd='vim --servername tmp'
alias vimserve='vim --servername tmp --remote'
alias htop='htop --no-mouse'
################################################################################
###########################  Use nvim for vim ##################################
#alias vim="nvim"
#alias vimdiff="nvim -d"
################################################################################
if [ -f ~/.config/bash/bash_aliases.local ]; then
    . ~/.config/bash/bash_aliases.local
fi
################################################################################
