[theme]
theme = "slick"
#theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block    = "battery"
interval = 10
format   = " $icon $percentage $time"

[[block]]
block = "backlight"

[[block]]
block     = "temperature"
interval  = 1

[[block]]
block    = "load"
interval = 2
format   = "$icon $1m $5m $15m"

[[block]]
block    = "cpu"
interval = 2

[[block]]
block    = "memory"
interval = 2
format   = "$icon $mem_used $mem_used_percents"

[[block]]
block = "sound"

[[block]]
block = "uptime"

[[block]]
block    = "time"
interval = 15
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
short = " $icon $timestamp.datetime(f:%R) "
